spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zona-salvaje_dev
    username: pvaldesoiro
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc.lob.non_contextual_creation: true