spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zona-salvaje_dev
    username: zona-salvaje
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        jdbc.lob.non_contextual_creation: true